INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (1, 'Julio Verne', 1);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (2, 'Miguel de Cervantes', 1);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (3, 'Wilbur Smith', 1);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (4, 'Robert Louis Stevenson', 1);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (5, 'Mark Twain', 1);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (6, 'Isaac Asimov', 2);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (7, 'H. G. Wells', 2);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (8, 'Ray Bradbury', 2);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (9, 'Arthur C. Clarke', 2);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (10, 'Philip K. Dick', 2);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (11, 'Mario Vargas Llosa', 3);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (12, 'Gabriel García Márquez', 3);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (13, 'Julio Cortázar', 3);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (14, 'Harper Lee', 3);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (15, 'John Steinbeck', 3);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (16, 'George R. R. Martin', 4);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (17, 'J. R. R. Tolkien', 4);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (18, 'Brandon Sanderson', 4);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (19, 'C. S. Lewis', 4);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (20, 'J. K. Rowling', 4);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (21, 'Ildefonso Falcones', 5);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (22, 'Arturo Pérez-Reverte', 5);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (23, 'Santiago Posteguillo', 5);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (24, 'Bernard Cornwell', 5);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (25, 'Ken Follett', 5);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (26, 'Marcela paz', 6);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (27, 'Charles Perrault /Hermanos grimm', 6);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (28, 'Oscar Wilde', 6);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (29, 'Horacio Quiroga', 6);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (30, 'Charles Dickens', 6);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (31, 'Arthur Conan Doyle', 7);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (32, 'Agatha Christie', 7);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (33, 'Dashiell Hammett', 7);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (34, 'Raymond Chandler', 7);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (35, 'Patricia Highsmith', 7);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (36, 'John le Carré', 7);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (37, 'Henning Mankell', 7);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (38, 'Camilla Läckberg', 7);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (39, 'Osvaldo Soriano', 7);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (40, 'Jeff Lindsay', 7);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (41, 'Juan Pablo Escobar', 7);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (42, 'Alfred Stewart', 7);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (43, 'Joel Dicker', 7);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (44, 'Sue Grafton', 7);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (45, 'Jorge Eduardo Benavides', 7);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (46, 'Alfonso del Río', 7);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (47, 'Johanna Lindsey', 8);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (48, 'Federico Moccia', 8);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (49, 'Nora Roberts', 8);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (50, 'Lisa Kleypas', 8);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (51, 'Megan Maxwell', 8);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (52, 'Edgar Allan Poe', 9);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (53, 'H.P. Lovecraft', 9);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (54, 'Stephen King', 9);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (55, 'John Ajvide Lindqvist', 9);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (56, 'Charles L. Grant', 9);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (57, 'Enrique Laso', 9);
INSERT INTO `author` (`id`,`name`, `genre_id`) VALUES (58, 'Bram Stoker', 9);