INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (1, 'Julio Verne', 1,1);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (2, 'Miguel de Cervantes', 1,2);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (3, 'Wilbur Smith', 1,3);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (4, 'Robert Louis Stevenson', 1,4);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (5, 'Mark Twain', 1,5);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (6, 'Isaac Asimov', 2,6);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (7, 'H. G. Wells', 2,7);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (8, 'Ray Bradbury', 2,8);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (9, 'Arthur C. Clarke', 2,9);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (10, 'Philip K. Dick', 2,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (11, 'Mario Vargas Llosa', 3,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (12, 'Gabriel García Márquez', 3,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (13, 'Julio Cortázar', 3,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (14, 'Harper Lee', 3,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (15, 'John Steinbeck', 3,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (16, 'George R. R. Martin', 4,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (17, 'J. R. R. Tolkien', 4,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (18, 'Brandon Sanderson', 4,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (19, 'C. S. Lewis', 4,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (20, 'J. K. Rowling', 4,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (21, 'Ildefonso Falcones', 5,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (22, 'Arturo Pérez-Reverte', 5,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (23, 'Santiago Posteguillo', 5,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (24, 'Bernard Cornwell', 5,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (25, 'Ken Follett', 5,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (26, 'Marcela paz', 6,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (27, 'Charles Perrault /Hermanos grimm', 6,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (28, 'Oscar Wilde', 6,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (29, 'Horacio Quiroga', 6,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (30, 'Charles Dickens', 6,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (31, 'Arthur Conan Doyle', 7,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (32, 'Agatha Christie', 7,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (33, 'Dashiell Hammett', 7,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (34, 'Raymond Chandler', 7,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (35, 'Patricia Highsmith', 7,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (36, 'John le Carré', 7,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (37, 'Henning Mankell', 7,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (38, 'Camilla Läckberg', 7,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (39, 'Osvaldo Soriano', 7,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (40, 'Jeff Lindsay', 7,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (41, 'Juan Pablo Escobar', 7,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (42, 'Alfred Stewart', 7,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (43, 'Joel Dicker', 7,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (44, 'Sue Grafton', 7,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (45, 'Jorge Eduardo Benavides', 7,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (46, 'Alfonso del Río', 7,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (47, 'Johanna Lindsey', 8,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (48, 'Federico Moccia', 8,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (49, 'Nora Roberts', 8,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (50, 'Lisa Kleypas', 8,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (51, 'Megan Maxwell', 8,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (52, 'Edgar Allan Poe', 9,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (53, 'H.P. Lovecraft', 9,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (54, 'Stephen King', 9,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (55, 'John Ajvide Lindqvist', 9,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (56, 'Charles L. Grant', 9,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (57, 'Enrique Laso', 9,0);
INSERT INTO `author` (`id`,`name`, `genre_id`, `hits`) VALUES (58, 'Bram Stoker', 9,0);