INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (1, '20.000 Leguas de Viaje Submarino', 1, 1,1);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (2, 'Cinco Semanas En Globo', 1, 1,2);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (3, 'De la Tierra a la Luna', 1, 1,3);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (4, 'Escuela de Robinsones', 1, 1,4);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (5, 'La Isla Misteriosa', 1, 1,5);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (6, 'La Vuelta al Mundo en 80 Días', 1, 1,6);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (7, 'Los Hijos del Capitán Grant', 1, 1,7);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (8, 'Miguel Strogoff', 1, 1,8);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (9, 'Don Quijote de la Mancha', 2, 1,9;
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (10, 'Los trabajos de Persiles y Sigismunda', 2, 1,10);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (11, 'La Galatea', 2, 1,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (12, 'El Destino del Cazador', 3, 1,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (13, 'El Faro del Fin del Mundo', 3, 1,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (14, 'El Séptimo Papiro', 3, 1,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (15, 'El Soberano del Nilo', 3, 1,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (16, 'El Triunfo del Sol', 3, 1,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (17, 'Horizonte Azul', 3, 1,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (18, 'La Ruta De Los Vengadores', 3, 1,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (19, 'Zorro Dorado', 3, 1,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (20, 'La Flecha Negra', 4, 1,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (21, 'La Isla Del Tesoro', 4, 1,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (22, 'Príncipe y Mendigo', 5, 1,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (23, 'Huckleberry Finn', 5, 1,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (24, 'Tom Sawyer', 5, 1,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (25, 'Trilogía de la Fundación', 6, 2,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (26, 'Yo, Robot', 6, 2,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (27, 'Las bóvedas de acero', 6, 2,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (28, 'El fin de la eternidad', 6, 2,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (29, 'El sol desnudo', 6, 2,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (30, 'Los propios dioses', 6, 2,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (31, 'La máquina del tiempo', 7, 2,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (32, 'El hombre invisible', 7, 2,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (33, 'La guerra de los mundos', 7, 2,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (34, 'La isla del doctor Moreau', 7, 2,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (35, 'Los primeros hombres en la luna', 7, 2,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (36, 'El alimento de los dioses', 7, 2,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (37, 'Crónicas marcianas', 8, 2,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (38, 'Fahrenheit 451', 8, 2,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (39, 'El hombre ilustrado', 8, 2,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (40, 'De la ceniza volverás', 8, 2,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (41, 'El Vino Del Estío', 8, 2,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (42, 'Remedio para Melancólicos', 8, 2,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (43, 'Una odisea espacial', 9, 2,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (44, 'Luz de otros días', 9, 2,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (45, 'Cánticos de la lejana Tierra', 9, 2,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (46, 'Las fuentes del paraíso', 9, 2,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (47, 'Expedición a la Tierra', 9, 2,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (48, 'El martillo de Dios', 9, 2,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (49, 'El hombre del castillo', 10, 2,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (50, 'Sueñan los androides con ovejas eléctricas', 10, 2,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (51, 'Palmer Eldritch', 10, 2,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (52, 'Tiempo de Marte', 10, 2,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (53, 'Fluyan mis lágrimas, dijo el policía', 10, 2,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (54, 'Una mirada a la oscuridad', 10, 2,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (55, 'La ciudad y los perros', 11, 3,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (56, 'La casa verde', 11, 3,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (57, 'Pantaleón y las visitadoras', 11, 3,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (58, 'La fiesta del Chivo', 11, 3,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (59, 'Travesuras de la niña mala', 11, 3,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (60, 'Cien años de soledad ', 12, 3,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (61, 'Del amor y otros demonios ', 12, 3,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (62, 'El amor en los tiempos del cólera ', 12, 3,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (63, 'El otoño del patriarca ', 12, 3,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (64, 'La hojarasca', 12, 3,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (65, 'Historias de cronopios y de famas', 13, 3,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (66, 'Todos los fuegos el fuego', 13, 3,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (67, 'El perseguidor y otros cuentos del cine', 13, 3,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (68, 'Salvo el crepúsculo', 13, 3,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (69, '62 Modelo para armar', 13, 3,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (70, 'Libro de Manuel', 13, 3,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (71, 'Matar un ruiseñor ', 14, 3,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (72, 'Ve y pon un centinela ', 14, 3,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (73, 'La luna se ha puesto', 15, 3,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (74, 'El autobús perdido', 15, 3,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (75, 'El invierno de mi descontento', 15, 3,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (76, 'De ratones y hombres', 15, 3,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (77, 'Las uvas de la ira', 15, 3,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (78, 'Canción de hielo y fuego', 16, 4,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (79, 'Danza de dragones', 16, 4,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (80, 'Sueño de primavera ', 16, 4,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (81, 'Fuego y sangre', 16, 4,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (82, 'Tormenta de espadas', 16, 4,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (83, 'El Silmarillion', 17, 4,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (84, 'Roverandom', 17, 4,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (85, 'La batalla del Campo del Este', 17, 4,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (86, 'El hobbit', 17, 4,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (87, 'El Señor de los Anillos', 17, 4,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (88, 'El camino de los reyes', 18, 4,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (89, 'Juramentada ', 18, 4,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (90, 'La Espada Infinita', 18, 4,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (91, 'Palabras Radiantes', 18, 4,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (92, 'steelheart', 18, 4,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (93, 'Trilogía cósmica', 19, 4,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (94, 'Las crónicas de Narnia', 19, 4,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (95, 'El príncipe Caspian', 19, 4,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (96, 'El sobrino del mago', 19, 4,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (97, 'La travesía del Viajero del Alba', 19, 4,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (98, 'Animales fantásticos y dónde encontrarlos', 20, 4,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (99, 'Harry Potter y la piedra filosofal', 20, 4,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (100, 'Harry Potter y las Reliquias de la Muerte', 20, 4,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (101, 'Harry Potter y el legado maldito', 20, 4,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (102, 'Harry Potter y el prisionero de Azkaban', 20, 4,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (103, 'La luna y el advenedizo', 21, 5,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (104, 'La catedral del mar', 21, 5,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (105, 'La mano de Fátima', 21, 5,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (106, 'La reina descalza', 21, 5,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (107, 'Los herederos de la tierra', 21, 5,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (108, 'de erfgenamen', 21, 5,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (109, 'El maestro de esgrima', 22, 5,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (110, 'La tabla de Flandes', 22, 5,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (111, 'El club Dumas', 22, 5,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (112, 'Las aventuras del capitán Alatriste', 22, 5,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (113, 'La carta esférica', 22, 5,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (114, 'Cabo Trafalgar', 22, 5,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (115, 'La legión perdida', 23, 5,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (116, 'La sangre de los libros', 23, 5,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (117, 'La noche en que Frankenstein leyó El Quijote', 23, 5,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (118, 'Africanus: el hijo del cónsul', 23, 5,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (119, 'Las legiones malditas', 23, 5,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (120, 'La traición de Roma', 23, 5,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (121, 'Crónicas del Señor de la Guerra', 24, 5,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (122, 'El rey del invierno', 24, 5,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (123, 'El trono vacante VIII', 24, 5,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (124, 'Arqueros del rey', 24, 5,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (125, 'Guerreros de la tormenta', 24, 5,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (126, 'Svein el del caballo blanco', 24, 5,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (127, 'Los pilares de la Tierra', 25, 5,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (128, 'Un mundo sin fin', 25, 5,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (129, 'Una columna de fuego', 25, 5,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (130, 'La caída de los gigantes', 25, 5,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (131, 'El invierno del mundo', 25, 5,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (132, 'El umbral de la eternidad', 25, 5,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (133, 'La isla de las tormentas', 25, 5,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (134, 'Papelucho', 26, 6,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (135, 'El soldadito rojo', 26, 6,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (136, 'Los Pecosos', 26, 6,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (137, 'A pesar de mi tía', 26, 6,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (138, 'Caramelos de luz', 26, 6,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (139, 'La vuelta de Sebastián', 26, 6,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (140, 'La caperucita Roja', 27, 6,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (141, 'Pulgarcito', 27, 6,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (142, 'La Cenicienta', 27, 6,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (143, 'La bella durmiente', 27, 6,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (144, 'El gato con botas', 27, 6,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (145, 'El gigante egoísta', 28, 6,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (146, 'El príncipe feliz', 28, 6,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (147, 'El ruiseñor y la rosa', 28, 6,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (148, 'El amigo fiel', 28, 6,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (149, 'El famoso cohete', 28, 6,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (150, 'La Gama Ciega', 29, 6,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (151, 'La Tortuga Gigante', 29, 6,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (152, 'Potro Salvaje', 29, 6,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (153, 'Oliver Twist', 30, 6,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (154, 'La pequeña Dorrit', 30, 6,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (155, 'El Armario Viejo', 30, 6,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (156, 'El Velo Negro', 30, 6,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (157, 'Una canción de Navidad', 30, 6,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (158, 'Estudio en escarlata', 31, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (159, 'El Signo de los Cuatro', 31, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (160, 'Las aventuras de Sherlock Holmes', 31, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (161, 'Las Memorias de Sherlock Holmes', 31, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (162, 'El Perro de los Baskerville', 31, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (163, 'El Regreso de Sherlock Holmes', 31, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (164, 'Diez negritos', 32, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (165, 'El misterioso caso de Styles', 32, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (166, 'Asesinato en el orient express', 32, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (167, 'Tres ratones ciegos', 32, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (168, 'Muerte en el Nilo', 32, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (169, 'El asesinato de Roger Acroyd', 32, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (170, 'Los cinco cerditos', 32, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (171, 'El halcón maltés', 33, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (172, 'Cosecha roja', 33, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (173, 'El hombre delgado', 33, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (174, 'La llave de cristal', 33, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (175, 'La maldición de los Dain', 33, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (176, 'Ciudad de pesadilla', 33, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (177, 'El largo adiós', 34, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (178, 'La dama del lago', 34, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (179, 'La ventana siniestra', 34, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (180, 'El simple arte de matar', 34, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (181, 'La historia de Poodle Springs', 34, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (182, 'Asesino en la lluvia', 34, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (183, 'El talento de Mr. Ripley', 35, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (184, 'Extraños en un tren', 35, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (185, 'El diario de Edith', 35, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (186, 'El muchacho que siguió a Ripley', 35, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (187, 'La máscara de Ripley', 35, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (188, 'El espía que surgió del frío', 36, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (189, 'Los perros de Riga', 37, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (190, 'La princesa de hielo', 38, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (191, 'Triste solitario y final ', 39, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (192, 'La muerte de Dexter', 40, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (193, 'Pablo Escobar In Fraganti', 41, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (194, 'Asesinato en el laberinto', 42, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (195, 'La desaparición de Stephanie Mailer', 43, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (196, 'Y de Yesterday', 44, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (197, 'El asesinato de Laura Olivo', 45, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (198, 'La ciudad de la lluvia', 46, 7,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (199, 'No traiciones a mi corazón', 47, 8,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (200, 'Corazón indómito', 47, 8,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (201, 'Tempestad salvaje', 47, 8,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (202, 'Ríndete, amor mío', 47, 8,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (203, 'Una dulce enemistad', 47, 8,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (204, 'Las trampas de la seducción', 47, 8,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (205, 'A tres metros sobre el cielo', 48, 8,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (206, 'Carolina se enamora', 48, 8,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (207, 'Esta noche dime que me quieres', 48, 8,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (208, 'Perdona pero quiero irme a Roma contigo', 48, 8,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (209, 'Perdona pero quiero casarme contigo', 48, 8,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (210, 'Aurora Boreal', 49, 8,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (211, 'El estigma del arrecife', 49, 8,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (212, 'Legado mágico', 49, 8,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (213, 'Una Muerte inmortal', 49, 8,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (214, 'Las estrellas de la fortuna', 49, 8,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (215, 'El bosque de Hollow', 49, 8,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (216, 'La antigua magia', 50, 8,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (217, 'El diablo tiene ojos azules', 50, 8,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (218, 'Un extraño en mis brazos', 50, 8,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (219, 'Mi nombre es Liberty', 50, 8,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (220, 'El diablo en invierno', 50, 8,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (221, 'Seducción al amanecer', 50, 8,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (222, 'Una flor para otra flor', 51, 8,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (223, 'Yo soy Eric Zimmerman', 51, 8,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (224, 'Pídeme lo que quieras y yo te lo daré', 51, 8,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (225, 'Soy una mamá divorciada y alocada', 51, 8,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (226, 'Adivina quién soy esta noche', 51, 8,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (227, 'Los príncipes azules también destiñen', 51, 8,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (228, 'El gato negro', 52, 9,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (229, 'El escarabajo de oro', 52, 9,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (230, 'El corazón delator', 52, 9,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (231, 'La caída de la casa Usher', 52, 9,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (232, 'La máscara de la muerte roja', 52, 9,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (233, 'Los crímenes de la calle Morgue', 52, 9,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (234, 'Las ratas en las paredes', 53, 9,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (235, 'En las montañas de la locura', 53, 9,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (236, 'La sombra sobre Innsmouth', 53, 9,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (237, 'La llamada de Cthulhu', 53, 9,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (238, 'El horror de Dunwich', 53, 9,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (239, 'El caso de Charles Dexter Ward', 53, 9,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (240, 'El misterio de Salem’s Lot', 54, 9,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (241, 'El nacimiento del pistolero', 54, 9,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (242, 'La Saga de la Torre Oscura', 54, 9,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (243, 'El viento por la cerradura', 54, 9,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (244, 'Canción de Susannah', 54, 9,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (245, 'La llegada de los tres', 54, 9,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (246, 'Déjame entrar', 55, 9,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (247, 'Puerto humano', 55, 9,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (248, 'Viento de sangre', 56, 9,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (249, 'Expediente X: Duendes', 56, 9,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (250, 'La última llamada del luto', 56, 9,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (251, 'Una tranquila noche de terror', 56, 9,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (252, 'El susurro de la medianoche', 56, 9,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (253, 'Desde el infierno (la trilogía)', 57, 9,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (254, 'Crímenes diabólicos', 57, 9,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (255, 'Dracula de Bram Stoker', 58, 9,0);
INSERT INTO `book` (`id`,`name`, `author_id`, `genre_id`,`hits`) VALUES (256, 'doctor Jekyll y el señor Hyde', 4, 9,0);