INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`,`population`) VALUES (0, 'España', 'Madrid',"TEST", 1,46659302);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`,`population`) VALUES (1, 'Argentina', 'Buenos Aires', "TEST", 1,44494502);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`,`population`) VALUES (2, 'Bolivia', 'Sucre',"TEST", 1,11217864);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`,`population`) VALUES (3, 'Brasil', 'Brasilia', "TEST", 1,208385000);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`,`population`) VALUES (4, 'Chile', 'Santiago',"TEST", 1,18751405);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`,`population`) VALUES (5, 'Colombia', 'Bogotá', "TEST", 1,45500000 );
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`,`population`) VALUES (6, 'Costa Rica', 'San José', "TEST", 1,5003000);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`,`population`) VALUES (7, 'Cuba', 'La Habana',"TEST", 1,11221060);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`,`population`) VALUES (8, 'Ecuador', 'Quito', "TEST", 1,	17267986);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`,`population`) VALUES (9, 'El Salvador','San Salvador',"TEST", 1,);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`,`population`) VALUES (10, 'Guatemala', 'Ciudad de Guatemala', "TEST", 1,17383245);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`,`population`) VALUES (11, 'Haití', 'Puerto Principe', "TEST", 1,10995182);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`,`population`) VALUES (12, 'Honduras','Tegucigalpa', "TEST", 1,	9265000);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`,`population`) VALUES (13, 'México', 'Mexico D.F',"TEST", 1,123982528);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`,`population`) VALUES (14, 'Nicaragua','Managua', "TEST", 1,6351956);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`,`population`) VALUES (15, 'Panamá','Panama' ,"TEST", 1,	4158783);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`,`population`) VALUES (16, 'Paraguay', 'Asuncion', "TEST", 1,7152703);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`,`population`) VALUES (17, 'Perú', 'Lima', "TEST", 1,32 162 184);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`,`population`) VALUES (18, 'Republica Dominicana', 'Santo Domingo', "TEST", 1,10766998);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`,`population`) VALUES (19, 'Uruguay', 'Montevideo', "TEST", 1, 3519014);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`,`population`) VALUES (20, 'Venezuela','Caracas', "TEST", 1,31828000);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`,`population`) VALUES (21, 'Puerto Rico', 'San Juan',"TEST", 1,3615086);
