INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`) VALUES (0, 'España', 'Madrid',"TEST", 1);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`) VALUES (1, 'Argentina', 'Buenos Aires', "TEST", 1);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`) VALUES (2, 'Bolivia', 'Sucre',"TEST", 1);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`) VALUES (3, 'Brasil', 'Brasilia', "TEST", 1);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`) VALUES (4, 'Chile', 'Santiago',"TEST", 1);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`) VALUES (5, 'Colombia', 'Bogotá', "TEST", 1);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`) VALUES (6, 'Costa Rica', 'San José', "TEST", 1);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`) VALUES (7, 'Cuba', 'La Habana',"TEST", 1);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`) VALUES (8, 'Ecuador', 'Quito', "TEST", 1);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`) VALUES (9, 'El Salvador','San Salvador',"TEST", 1);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`) VALUES (10, 'Guatemala', 'Ciudad de Guatemala', "TEST", 1);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`) VALUES (11, 'Haití', 'Puerto Principe', "TEST", 1);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`) VALUES (12, 'Honduras','Tegucigalpa', "TEST", 1);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`) VALUES (13, 'México', 'Mexico D.F',"TEST", 1);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`) VALUES (14, 'Nicaragua','Managua', "TEST", 1);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`) VALUES (15, 'Panamá','Panama' ,"TEST", 1);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`) VALUES (16, 'Paraguay', 'Asuncion', "TEST", 1);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`) VALUES (17, 'Perú', 'Lima', "TEST", 1);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`) VALUES (18, 'Republica Dominicana', 'Santo Domingo', "TEST", 1);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`) VALUES (19, 'Uruguay', 'Montevideo', "TEST", 1);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`) VALUES (20, 'Venezuela','Caracas', "TEST", 1);
INSERT INTO `country` (`id`, `name`,`capital`, `polygon`,`hits`) VALUES (21, 'Puerto Rico', 'San Juan',"TEST", 1);
